### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake

### ISSUE THREAD

**Issue by gameboys88** [abdlhay/AbyssVideoDownloader#10]
Có vẻ như phía host đã thêm thuật toán chặn download.
Nhờ bạn tìm hiểu giúp:

```
java -jar abyss-dl.jar --header "Referer: https://abyss.to/" -c 5 -o tghm022.mp4
https://tvphim.id/xem-phim/thoi-gioi-hoan-my-538031
```

```
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141)
        at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source)
        at org.jsoup.helper.HttpConnection.execute(Unknown Source)
        at org.jsoup.helper.HttpConnection.get(Unknown Source)
        at com.abmo.f.b.a(Unknown Source)
        at com.abmo.d.i.a(Unknown Source)
        at com.abmo.MainKt.a(Unknown Source)
        at com.abmo.d.a(Unknown Source)
        at com.abmo.d.invoke(Unknown Source)
        at kotlin.c.a.d.a(Unknown Source)
        at kotlin.c.b.a.a.b(Unknown Source)
        at kotlin.c.i.a(Unknown Source)
        at kotlin.c.b.a.n.a(Unknown Source)
        at com.abmo.MainKt.main(Unknown Source)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        ... 20 more
```

![image](https://github.com/user-attachments/assets/86c58de3-cc5f-4352-b00a-91e4f0fc681b)

**Comment by abdlhay** [comment]
Does the problem still occur?

**Comment by gameboys88** [comment]
Yes it does. Please fix it.

**Comment by abdlhay** [comment]
What version of the JDK are you using to run the JAR file?
are you currently using a proxy or VPN on your machine?

**Comment by gameboys88** [comment]
I use JDK 21.0.4, no proxy or VPN added. 
The day before I was still able to download normally until episode 21, the next day when I downloaded episode 22 I got the above error.

**Comment by abdlhay** [comment]
download latest jar and give it another try 
see if it's working

**Comment by gameboys88** [comment]
It's work. Thank you very much!

**Comment by gameboys88** [comment]
Hôm qua mình down bình thường nhưng hôm nay lại bị lỗi 
```
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
```
giống ở trên.

Sau đó mình lên đây lấy file mới nhất về thì khi chạy lệnh down
```
java -jar abyss-dl.jar --header "Referer: https://abyss.to/" -c 5 -o tghm160.mp4
```
Rồi Enter thì bị lỗi
```
ERROR: Video with ID --header not found
```
Link down: https://tvphim.li/xem-phim/thoi-gioi-hoan-my-616420

![image](https://github.com/user-attachments/assets/310bc889-fc62-4e83-b11f-bfe7dd840c51)

Nhờ bạn check lại giúp.

**Comment by gameboys88** [comment]
Mình lấy lại file cũ ver 1.4 thì lại down được bình thường rồi.
Chắc do hôm qua đổi tên miền từ **tvphim.li** sang **tvphim.bz** nên bị như vậy.
Cảm ơn bạn!
