### ISSUE TITLE
Error File

### ISSUE THREAD

**Issue by kukhanh29** [abdlhay/AbyssVideoDownloader#11]
same Url error:
```
https://short.ink/ZvpFFKGrW
https://short.ink/o3rJ-FYHD
https://short.ink/-xdfMhFId
```

![error](https://github.com/user-attachments/assets/c98f2778-707d-4b56-a2d6-4d8e39d1a3f8)

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:672)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at com.abmo.b.compare(Unknown Source)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1234)
	at kotlin.a.o.a(Unknown Source)
	at kotlin.a.B.a(Unknown Source)
	at com.abmo.MainKt.a(Unknown Source)
	at com.abmo.d.a(Unknown Source)
	at com.abmo.d.invoke(Unknown Source)
	at kotlin.c.a.d.a(Unknown Source)
	at kotlin.c.b.a.a.b(Unknown Source)
	at kotlin.c.i.a(Unknown Source)
	at kotlin.c.b.a.n.a(Unknown Source)
	at com.abmo.MainKt.main(Unknown Source)

```

**Comment by abdlhay** [comment]
this issue is already fixed #7
please download the latest jar file from release page
