### ISSUE TITLE
not working for my video id

### ISSUE THREAD

**Issue by VLiulian** [abdlhay/AbyssVideoDownloader#7]
Comand :

java -jar abyss-dl.jar

Output:

Enter the video URL or ID (e.g., K8R6OOjS7):
goUsCFl20
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:672)
        at java.base/java.lang.Integer.parseInt(Integer.java:778)
        at com.abmo.b.compare(Unknown Source)
        at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.base/java.util.TimSort.sort(TimSort.java:220)
        at java.base/java.util.Arrays.sort(Arrays.java:1234)
        at kotlin.a.o.a(Unknown Source)
        at kotlin.a.B.a(Unknown Source)
        at com.abmo.MainKt.a(Unknown Source)
        at com.abmo.d.a(Unknown Source)
        at com.abmo.d.invoke(Unknown Source)
        at kotlin.c.a.d.a(Unknown Source)
        at kotlin.c.b.a.a.b(Unknown Source)
        at kotlin.c.i.a(Unknown Source)
        at kotlin.c.b.a.n.a(Unknown Source)
        at com.abmo.MainKt.main(Unknown Source)

Thanks for the script it works with K8R6OOjS7
But not with:
 https://playhydrax.com/?v=goUsCFl20

My system Debian 12

**Comment by VLiulian** [comment]
It works great thanks!
